/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationBar: typeof import('./src/components/Dashboard/NavigationBars/ApplicationBar.vue')['default']
    ButtonTheme: typeof import('./src/components/Dashboard/NavigationBars/ButtonTheme.vue')['default']
    DrawerBar: typeof import('./src/components/Dashboard/NavigationBars/DrawerBar.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavigationBars: typeof import('./src/components/Dashboard/NavigationBars/index.vue')['default']
    QrCodeScan: typeof import('./src/components/Dashboard/QrCodeScan.vue')['default']
    ReloadPWA: typeof import('./src/components/ReloadPWA.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/Authentication/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/Authentication/SignUpForm.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
  }
}
